Controllers/SignUpController.cs
using Microsoft.AspNetCore.Mvc;
using FinanceManagementApp.Models;
using System.Data.SqlClient;
using System.Text.RegularExpressions;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Text;
using System.Security.Claims;

namespace FinanceManagementApp.Controllers
{
    [Route("signup")]
    public class SignUpController : Controller
    {
        private readonly IConfiguration _configuration;

        public SignUpController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        [HttpGet]
        public IActionResult SignUp()
        {
            return View("~/Views/App/SignUp.cshtml", new User());
        }

        [HttpPost]
        public IActionResult CreateUser(string first_name, string last_name, string email_address, string password, string confirm_password)
        {
            User user = new User
            {
                FirstName = first_name,
                LastName = last_name,
                EmailAddress = email_address,
                Password = password
            };

            if (string.IsNullOrWhiteSpace(first_name) ||
                string.IsNullOrWhiteSpace(last_name) ||
                string.IsNullOrWhiteSpace(email_address) ||
                string.IsNullOrWhiteSpace(password))
            {
                ViewData["ErrorMessage"] = "All fields are required";
                return View("~/Views/App/SignUp.cshtml", user);
            }

            if (password.Length < 4)
            {
                ViewData["ErrorMessage"] = "Password must be at least 4 characters";
            }

            var passwordRegex = new Regex(@"^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\W_]).+$");
            if (!passwordRegex.IsMatch(password))
            {
                ViewData["ErrorMessage"] = "Password must contain at least one letter, one number, and one special character.";
                return View("~/Views/App/SignUp.cshtml", user);
            }

            if (password != confirm_password)
            {
                ViewData["ErrorMessage"] = "Passwords do not match";
                return View("~/Views/App/SignUp.cshtml", user);
            }

            user.Password = BCrypt.Net.BCrypt.HashPassword(user.Password);
            
            try
            {
                string connectionString = _configuration["ConnectionStrings:DefaultConnection"];

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    string query = "INSERT INTO users " +
                                   "(user_first_name, user_last_name, user_email_address, user_password) VALUES" +
                                   "(@first_name, @last_name, @email_address, @password);";

                    using (SqlCommand command = new SqlCommand(query, connection))
                    {
                        command.Parameters.AddWithValue("@first_name", user.FirstName);
                        command.Parameters.AddWithValue("@last_name", user.LastName);
                        command.Parameters.AddWithValue("@email_address", user.EmailAddress);
                        command.Parameters.AddWithValue("@password", user.Password);

                        command.ExecuteNonQuery();
                    } 
                }

                var secretKey = _configuration["JwtSettings:SecretKey"];

                var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(secretKey));
                var credentials = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);

                var tokenDescriptor = new SecurityTokenDescriptor
                {
                    Subject = new ClaimsIdentity(new[]
                    {
                        new Claim("sub", email_address),
                        new Claim("email_address", email_address)
                    }),
                    Expires = DateTime.UtcNow.AddHours(2),
                    SigningCredentials = credentials
                };

                var tokenHandler = new JwtSecurityTokenHandler();
                var token = tokenHandler.CreateToken(tokenDescriptor);
                string jwtToken = tokenHandler.WriteToken(token);

                var cookieOptions = new CookieOptions
                {
                    HttpOnly = true,
                    Expires = DateTime.UtcNow.AddHours(2),
                    Secure = true,
                    SameSite = SameSiteMode.Strict
                };
                Response.Cookies.Append("jwtToken", jwtToken, cookieOptions);

                return RedirectToAction("FinanceOverview", "FinanceOverview");

            }
            catch (Exception ex) 
            {
                ViewData["ErrorMessage"] = ex.Message;
                return View("~/Views/App/SignUp.cshtml", user);
            }
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using FinanceManagementApp.Models;
using System.Data.SqlClient;

namespace FinanceManagementApp.Controllers
{
    [Route("user")]
    public class UserController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly HandleToken _handleToken;

        public UserController(IConfiguration configuration)
        {
            _configuration = configuration;
            _handleToken = new HandleToken(configuration);
        }

        [HttpPost("edituserform")]
        public IActionResult EditUserForm()
        {
            string jwtToken = Request.Cookies["jwtToken"];
            bool isTokenValid = _handleToken.IsTokenValid(jwtToken);

            if (!isTokenValid)
            {
                return RedirectToAction("Login", "Login");
            }

            var userId = _handleToken.ExtractIdFromToken(jwtToken);

            try
            {
                string connectionString = _configuration["ConnectionStrings:DefaultConnection"];

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    string findUserQuery = "SELECT TOP 1 user_first_name, user_last_name, user_email_address " +
                                      "FROM users " +
                                      "WHERE user_id=@user_id";

                    using (SqlCommand command = new SqlCommand(findUserQuery, connection))
                    {
                        command.Parameters.AddWithValue("@user_id", userId);

                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            if (reader.Read())
                            {
                                User user = new User
                                {
                                    Id = Convert.ToInt32(userId),
                                    FirstName = reader.GetString(0),
                                    LastName = reader.GetString(1),
                                    EmailAddress = reader.GetString(2)
                                };

                                return View("~/Views/App/EditUserForm.cshtml", user);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                return RedirectToAction("FinanceOverview", "FinanceOverview");
            }

            ViewData["ErrorMessage"] = "Error loading user information...";
            return RedirectToAction("FinanceOverview", "FinanceOverview");
        }

        [HttpPost("edituser")]
        public IActionResult EditUser(int id, string first_name, string last_name, string email_address)
        {
            string jwtToken = Request.Cookies["jwtToken"];
            bool isTokenValid = _handleToken.IsTokenValid(jwtToken);

            if (!isTokenValid)
            {
                return RedirectToAction("Login", "Login");
            }

            User user = new User
            {
                Id = id,
                FirstName = first_name,
                LastName = last_name,
                EmailAddress = email_address
            };

            if (string.IsNullOrEmpty(first_name) ||
                string.IsNullOrEmpty(last_name) ||
                string.IsNullOrEmpty(email_address)) 
            {
                ViewData["ErrorMessage"] = "All fields are required";
                return View("~/Views/App/EditUserForm.cshtml", user);
            }

            try
            {
                string connectionString = _configuration["ConnectionStrings:DefaultConnection"];

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    string findUserQuery = "UPDATE users " +
                                      "SET user_first_name=@first_name, user_last_name=@last_name, user_email_address=@email_address " +
                                      "WHERE user_id=@user_id;";

                    using (SqlCommand command = new SqlCommand(findUserQuery, connection))
                    {
                        command.Parameters.AddWithValue("@first_name", user.FirstName);
                        command.Parameters.AddWithValue("@last_name", user.LastName);
                        command.Parameters.AddWithValue("@email_address", user.EmailAddress);
                        command.Parameters.AddWithValue("@user_id", user.Id);

                        command.ExecuteNonQuery();
                    }
                }

                return RedirectToAction("FinanceOverview", "FinanceOverview");
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                return View("~/Views/App/EditUserForm.cshtml", user);
            }
        }

        [HttpPost("deleteuser")]
        public IActionResult DeleteUser(int id)
        {
            string jwtToken = Request.Cookies["jwtToken"];
            bool isTokenValid = _handleToken.IsTokenValid(jwtToken);

            if (!isTokenValid)
            {
                return RedirectToAction("Login", "Login");
            }

            try
            {
                string connectionString = _configuration["ConnectionStrings:DefaultConnection"];

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    string deleteUserQuery = "DELETE FROM users WHERE user_id=@user_id;";

                    using (SqlCommand command = new SqlCommand(deleteUserQuery, connection))
                    {
                        command.Parameters.AddWithValue("@user_id", id);

                        int rowsAffected = command.ExecuteNonQuery();

                        if (rowsAffected > 0)
                        {
                            Response.Cookies.Delete("jwtToken");
                            return RedirectToAction("Index", "Home");
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = "Error deleting user: " + ex.Message;
            }
            return RedirectToAction("FinanceOverview");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinanceManagementApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinanceManagementApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinanceManagementApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="SignUp" asp-action="SignUp">Sign up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Login" asp-action="LoginForm">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FinanceManagementApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_NoNavBarLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinanceManagementApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinanceManagementApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <p class="navbar-brand">FinanceManagementApp</p>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <form action="@Url.Action("Logout", "FinanceOverview")" method="POST">
                                <button type="submit" class="nav-link btn btn-danger">Logout</button>
                            </form>
                        </li>
                        <li class="nav-item" style="margin-left: 2rem">
                            <form action="@Url.Action("EditUserForm", "User")" method="POST">
                                <button type="submit" class="nav-link btn btn-secondary">Edit profile</button>
                            </form>
                        </li>
                        <li class="nav-item" style="margin-left: 2rem">
                            <a href="@Url.Action("FinanceReportView", "FinanceReport")" class="nav-link btn btn-info">View yearly reports</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FinanceManagementApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>